from hgvs.sequencevariant import SequenceVariant
from hgvs.variantmapper import VariantMapper

class AssemblyMapper(VariantMapper):
    def g_to_c(self, var_g: SequenceVariant, tx_ac: str) -> SequenceVariant: ...
    def g_to_n(self, var_g: SequenceVariant, tx_ac: str) -> SequenceVariant: ...
    def g_to_t(self, var_g: SequenceVariant, tx_ac: str) -> SequenceVariant: ...
    def c_to_g(self, var_c: SequenceVariant) -> SequenceVariant: ...
    def n_to_g(self, var_n: SequenceVariant) -> SequenceVariant: ...
    def t_to_g(self, var_t: SequenceVariant) -> SequenceVariant: ...
