name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cancel-previous:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: khan/pull-request-workflow-cancel@1.0.0
        with:
          workflows: "main.yml"
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: 'true'

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pipenv"
          cache-dependency-path: |
            Pipfile.lock

      - name: Install pipenv and deps
        run: |
          python -m pip install --upgrade pipenv wheel
          make deps

      - name: Lint source code
        run: make lint

  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.10'
          - '3.11'
    needs: linting
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: 'true'

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pipenv"
          cache-dependency-path: |
            Pipfile.lock

      - name: Install pipenv and deps
        run: |
          python -m pip install --upgrade pipenv wheel
          make deps

      - name: Install dependencies
        run: make deps

      - name: Run tests
        run: make test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
